name: Manual Migration Example

on:
  workflow_dispatch:
    inputs:
      database-url:
        description: 'Database URL (use secrets.DATABASE_URL for sensitive data)'
        required: true
        type: string
        default: 'postgresql://user:password@localhost:5432/mydb'
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development
      dry-run:
        description: 'Run in preview mode (recommended for production)'
        required: false
        type: boolean
        default: true

jobs:
  migrate:
    name: Migrate ${{ github.event.inputs.environment }} Database
    uses: ./.github/workflows/prisma-migrate.yml
    with:
      database-url: ${{ github.event.inputs.database-url }}
      schema-path: 'prisma/schema.prisma'
      prisma-version: 'latest'
      dry-run: ${{ github.event.inputs.dry-run }}
      working-directory: '.'
    secrets:
      # Use repository secrets for sensitive database URLs
      database-urls: ${{ secrets[format('{0}_DATABASE_URL', upper(github.event.inputs.environment))] }}
